monitor_index: 2
dpi_scale: 1.0
screen:
  width: null
  height: null
window:
  title: L9ASIA
  require_foreground: true
  require_maximized: true
  auto_focus: true
  force_to_monitor_index: 2
  click_to_focus: true
keybinds:
  interact: e
  confirm: enter
  open_shop: i
  close_ui: esc
  return_to_town: r
  map: m
  autobattle: g
  inventory: b
  move_up: w
  move_left: a
  move_down: s
  move_right: d
  panic_key: shift+escape
match:
  method: TM_CCOEFF_NORMED
  use_color: false
  multi_scale: true
  scales:
  - 0.7
  - 0.8
  - 0.9
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  default_threshold: 0.85
  nms_iou: 0.3
  max_results: 5
threshold_overrides: {}
buy_potions:
  empty_check_samples: 5
  empty_check_min_matches: 4
  empty_check_interval_ms: 150
  use_pyautogui_locate: true
  pyauto_threshold: 0.9
  pyauto_fullscreen: true
  color:
    red_ratio_has: 0.06
    red_ratio_empty: 0.02
    sat_thresh: 60
    val_thresh: 50
timings:
  wait_min_ms: 60
  wait_max_ms: 120
  default_timeout_s: 5.0
  detection_timeout_s: 3.0
  action_retry_count: 3
  action_retry_backoff_s: 0.5
  pathing_wait_s: 6.0
  shop_open_timeout_s: 12.0
  return_town_timeout_s: 20.0
  teleport_min_wait_s: 3.5
  teleport_post_wait_min_s: 2.0
  teleport_post_wait_max_s: 3.0
  confirm_timeout_s: 8.0
  close_wait_s: 2.0
  post_store_delay_s: 1.0
  random_action_pause: true
  action_pause_min_ms: 1000
  action_pause_max_ms: 3000
rois:
  minimap_anchor:
  - 0.8
  - 0.0
  - 1.0
  - 0.2
  hud_anchor:
  - 0.0
  - 0.8
  - 1.0
  - 1.0
  revive_ui:
  - 0.25
  - 0.2
  - 0.75
  - 0.85
  center_ui:
  - 0.2
  - 0.2
  - 0.8
  - 0.8
debug:
  enabled: true
  screenshot_on_failure: true
  dir: ./debug
  log_level: INFO
  screenshot_format: png
  save_best_on_miss: true
input:
  prefer_direct: true
  hold_ms: 80
  press_repeats: 3
  repeat_interval_ms: 70
  mouse_hold_ms: 150
  mouse_move_duration_ms: 250
  mouse_move_duration_ms_min: 200
  mouse_move_duration_ms_max: 450
  use_wm_messages: true
  fire_all_click_backends: true
  wiggle_before_click: true
  click_repeats: 1
  click_interval_ms: 80
grind:
  area_id: default
  area_template: l9/assets/grind/area.png
  teleporter_template: l9/assets/grind/teleporter.png
  fast_travel_template: l9/assets/grind/fast_travel.png
  pyauto_threshold: 0.9
  record_stop_key: f12
  record_split_key: f9
  record_keys:
  - w
  - a
  - s
  - d
  - e
  - z
  - m
  - esc
  bag_icon_template: l9/assets/ui/hud/bag_icon.png
  bag_icon_timeout_s: 12.0
  bag_icon_roi: hud_anchor
  spots:
  - id: 1
    name: BoT
    region_template: l9/assets/grind/spots/spot1/region.png
    area_template: l9/assets/grind/spots/spot1/area.png
    teleporter_template: l9/assets/grind/spots/spot1/teleporter.png
    fast_travel_template: l9/assets/grind/spots/spot1/fast_travel.png
    confirm_template: l9/assets/grind/spots/spot1/confirm.png
  - id: 2
    name: ToT2f
    region_template: l9/assets/grind/spots/spot2/region.png
    area_template: l9/assets/grind/spots/spot2/area.png
    teleporter_template: l9/assets/grind/spots/spot2/teleporter.png
    fast_travel_template: l9/assets/grind/spots/spot2/fast_travel.png
    confirm_template: l9/assets/grind/spots/spot2/confirm.png
  - id: 3
    name: PoR
    region_template: l9/assets/grind/spots/spot3/region.png
    area_template: l9/assets/grind/spots/spot3/area.png
    teleporter_template: l9/assets/grind/spots/spot3/teleporter.png
    fast_travel_template: l9/assets/grind/spots/spot3/fast_travel.png
    confirm_template: l9/assets/grind/spots/spot3/confirm.png
  active_spot_id: 3
revive:
  revive_button: l9/assets/revive/revive_button.png
  stat_reclaim_button: l9/assets/revive/stat_reclaim.png
  retrieve_button: l9/assets/revive/retrieve.png
  pyauto_threshold: 0.9
  revive_timeout_s: 2.0
  reclaim_timeout_s: 3.0
  retrieve_timeout_s: 3.0
dungeon:
  gates: []
multi_screen: true
